print "All good things come to those who wait.".split(' ')
print "All,good,things,come,to,those,who,wait.".split(',')
print "All<>good<>things<>come<>to<>those<>who<>wait.".split('<>')
print "All<>good<>things<>come<>to<>those<>who<>wait.".split(' ')
print '1<>2<>3'.split('<>')